# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experiences
    url: '#experiences'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Awards
    url: '#awards'
    weight: 50
  # - name: Projects
  #   url: '#projects'
  #   weight: 60
  # - name: Posts
  #   url: '#posts'
  #   weight: 70
  - name: Contact
    url: '#contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  # - name: CV
  #   url: uploads/resume_full.pdf
  #   weight: 90
