# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Machine learning researcher and software engineer.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: 'G-SXCTNPBPNK'
    baidu_tongji: ''
    google_tag_manager: 'G-SXCTNPBPNK'
    microsoft_clarity: ''  
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Bo-Wen Chen. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
    extra_languages: 
      - cpp
      - python
      - javascript
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/EdwinYam/EdwinYam.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: giscus
    commentable:
      page: true
      post: true
      docs: false
      project: true
      publication: true
      talk: false
    disqus:
      shortname: edwinyam
      show_count: true
    commento:
      url: ''
    giscus:
      repo: "EdwinYam/EdwinYam.github.io"
      repo_id: "R_kgDOJxSuEQ"
      category: "Announcements"
      category_id: "DIC_kwDOJxSuEc4CXg8z"
      mapping: "pathname"
      label: "comment"
      theme: preferred_color_scheme
      reactions_enabled: "1"
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
